version: "3"

services:

  redis:
    container_name: dubhacks_redis
    hostname: dubhacks_redis
    image: redis:5.0.6-buster
    ports:
      - "6379:6379"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.3

  node:
    container_name: dubhacks_node
    hostname: dubhacks_node
    build:
      context: ./node
      dockerfile: ../docker/node/Dockerfile
    image: "dubhacks_node"
    command: "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - ./node:/dubhacks/backend/node/
      - /dubhacks/backend/node/node_modules
    ports:
      - "8080:8080"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.2
    depends_on:
      - redis

networks:
  dubhacks_net:
    driver: bridge
    ipam:
      config:
        - subnet: 175.0.0.0/16
