version: "3"

services:
  redis:
    container_name: dubhacks_redis
    hostname: dubhacks_redis
    image: redis:5.0.6-buster
    ports:
      - "6379:6379"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.3

  node:
    container_name: dubhacks_node
    hostname: dubhacks_node
    build:
      context: ./node
      dockerfile: ../docker/node/Dockerfile
    image: "dubhacks_node"
    command: "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - ./node:/dubhacks/backend/node/:Z
      - /dubhacks/backend/node/node_modules
    ports:
      - "8080:8080"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.2
    depends_on:
      - redis

  recognition:
    container_name: dubhacks_recognition
    hostname: dubhacks_recognition
    build:
      context: ./recognition
      dockerfile: ../docker/recognition/Dockerfile
    image: "dubhacks_recognition"
    command: "python3 models/python/predict.py"
    stdin_open: true
    tty: true
    volumes:
      - ./recognition:/dubhacks/backend/recognition/:Z
    ports:
      - "5000:5000"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.4
    depends_on:
      - node

  navigator:
    container_name: dubhacks_navigator
    hostname: dubhacks_navigator
    build:
      context: ./navigator
      dockerfile: ../docker/navigator/Dockerfile
    image: "dubhacks_navigator"
    command: "python3 app.py"
    stdin_open: true
    tty: true
    volumes:
      - ./navigator:/dubhacks/backend/navigator/:Z
    ports:
      - "5050:5050"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.5
    depends_on:
      - node

  imager:
    container_name: dubhacks_imager
    hostname: dubhacks_imager
    build:
      context: ./imager
      dockerfile: ../docker/imager/Dockerfile
    image: "dubhacks_imager"
    command: "python3 app.py"
    stdin_open: true
    tty: true
    volumes:
      - ./imager:/dubhacks/backend/imager/:Z
      - ./mediafiles/images:/dubhacks/backend/imager/images:Z
    ports:
      - "5080:5080"
    networks:
      dubhacks_net:
        ipv4_address: 175.0.0.6
    depends_on:
      - node

networks:
  dubhacks_net:
    driver: bridge
    ipam:
      config:
        - subnet: 175.0.0.0/16
